suffix = ''    # Суффикс после имени оригинальной дорожки
fromdir = r'C:\source\\'
todir = r'C:\source\\'
need_encode = True      # Видео будет скодировано
need_fix = False        # Дорожки не будут исправлены и переименованы
create_opus = False      # opus не нужен
prepare = True          # Будут подготовлены файлы без звука. Только видеодорожка.
need_merge = False             # Собираем матрешку в штатном режиме
is51 = False     #Будет подготовлен звук из дорожки 2.0
tmp_dir = r'C:\temp\\'
ffmpeg = r'C:\Program Files\ffmpeg\bin\ffmpeg.exe'
mkvpropedit = r'C:\Program Files\MKVToolNix\mkvpropedit.exe'
mkvmerge = r'C:\Program Files\MKVToolNix\mkvmerge.exe'
rename_mask_from = '].mkv'
rename_mask_to = '_HEVC].mkv'
lang = 'jpn'
